### ISSUE TITLE
Support iterating through a collection

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#28] opened 2016-01-04 23:04 UTC
Currently, there is no way to iterate through all elements in a set/map/stack.

Not sure how it will look like.
I guess something like foreach (e : coll) ... would not be allowed in Boa. Maybe foreach (e in coll) ...

**Comment by psybers** [comment] 2016-01-05 05:56
Duplicate of issue #5.

**Closed by psybers** 2016-01-05 05:56 UTC
Labels: enhancement
