### ISSUE TITLE
User defined function puts all variables in global scope, which causes user to create different names for each variable even if variable scope are not intersecting

### ISSUE THREAD

**Issue by nmtiwari** [boalang/compiler#104] opened 2017-02-20 04:48 UTC
Attached Boa program has one user function to demonstrate the problem. 
[error.txt](https://github.com/boalang/compiler/files/786568/error.txt)
[gen.txt](https://github.com/boalang/compiler/files/786571/gen.txt)

**Comment by psybers** [comment] 2017-02-20 15:10
Isn't this just a duplicate of #25?

**Closed** 2017-03-02 14:57 UTC
Labels: duplicate
