### ISSUE TITLE
Code gen error for getName in boa.types.Ast.Type

### ISSUE THREAD

**Issue by ankuraga1508** [boalang/compiler#49] opened 2016-05-10 18:33 UTC
```
USES: output collection[string][string][time] of int;
p: Project = input;

project_url := p.project_url;
file_name: string;
commit_date: time;

diamond := visitor {
	before node: ChangedFile -> {
		if (!iskind("SOURCE_JAVA_JLS", node.kind))
			stop;
		file_name = node.name;
	}
	before node: Revision -> commit_date = node.commit_date;
	before node: Type ->
		if (strfind("<>", node.name) > -1)
			USES[project_url][file_name][commit_date] << 1;
};

visit(p, diamond);
```
```
error: method indexOf in class BoaStringIntrinsics cannot be applied to given types;
						if (boa.functions.BoaStringIntrinsics.indexOf("<>", ___node.getName()) > -1l)
						                                     ^
  required: String,String
  found: String,int
```

Return type for ___node.getName() is int should be String. Similar issue as in #48

**Comment by psybers** [comment] 2016-05-10 19:21
Duplicate of #48

**Closed by psybers** 2016-05-10 19:21 UTC
Labels: bug, duplicate
