### ISSUE TITLE
Code generation error as map key

### ISSUE THREAD

**Issue by ankuraga1508** [boalang/compiler#50] opened 2016-05-10 18:38 UTC
```
Counts: output sum of int;
Projects: output sum[string] of int;
p: Project = input;

types: map[string] of int;

visit(p, visitor {
	before n: Declaration -> {
		exists (i: int; n.parents[i].name == "Runnable"
				|| n.parents[i].name == "Thread"
				|| n.parents[i].name == "TimerTask"
				|| n.parents[i].name == "Executor"
				|| n.parents[i].name == "ExecutorService"
				|| n.parents[i].name == "ScheduledExecutorService"
				|| n.parents[i].name == "AbstractExecutorService"
				|| n.parents[i].name == "ThreadPoolExecutor"
				|| n.parents[i].name == "ScheduledThreadPoolExecutor"
				|| match(`^Callable($|<.*>$)`, n.parents[i].name))
			types[n.parents[i].name] = 1;
		exists (i: int; match(`^Callable($|<.*>$)`, n.parents[i].name))
			types["Callable"] = 1;
	}
});

if (len(types) > 0) {
	haslog := false;
	visit(p, visitor {
		before n: Revision -> {
			if (match(`\b(race|deadlock|violation|deadlocking)\b`, n.log))
				haslog = true;
			stop;
		}
	});
	if (haslog) {
		Counts << 1;
		Projects[p.id] << 1;
	}
}
```
```
error: illegal start of expression
___types.put(___n.getParentsList().get(___i)).getName(, 1l);}
```

SImilar issue as in #1

**Comment by psybers** [comment] 2016-05-10 19:21
Duplicate of #1

**Closed by psybers** 2016-05-10 19:21 UTC
Labels: bug, duplicate
